[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/old-home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/old-blog"
  to = "/profile"
  status = 301
  force = true

[[redirects]]
  from = "/nonsense"
  to = "/blog"
  status = 302
  force = true

# Category redirects are now handled by Edge Functions for complex logic
# See netlify/edge-functions/category-redirects.ts

# Temporarily disabled Edge Function to test React routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# SPA fallback - must be last to avoid interfering with Edge Functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
