[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/old-home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/old-blog"
  to = "/profile"
  status = 301
  force = true

[[redirects]]
  from = "/nonsense"
  to = "/blog"
  status = 302
  force = true

# Category redirects are now handled by Edge Functions for complex logic
# See netlify/edge-functions/category-redirects.ts

# Ensure Spanish archive paths don't get re-redirected (short-circuit)
[[redirects]]
  from = "/archive/es"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/archive/es/*"
  to = "/index.html"
  status = 200

# Redirect visitors with Spanish language preference to the Spanish archive
[[redirects]]
  from = "/archive/*"
  to = "/archive/es/:splat"
  status = 302
  conditions = {Language = ["es", "es-es", "es-ar", "es-mx", "es-419"]}

# SPA fallback - must be last to avoid interfering with Edge Functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
